// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateSearchProperties.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum;

/**
 * Stores the embedded values and asssociations of all entities in the system by type.  
 * Is used to determine the appropriate parameter name when an embedded value's property 
 * is referenced as the attribute to search by (as opposed to an association).
 * 
 * @author Chad Brandon
 */
 @SuppressWarnings({"unchecked"})
public class CriteriaSearchProperties
{
    private static final java.util.Map embeddedValuesByType = new java.util.HashMap();
    private static final java.util.Map navigableAssociationEndsByType = new java.util.HashMap();
    
    static
    {
        initialize1();
        initialize2();
        initialize3();
        initialize4();
        initialize5();
        initialize6();
        initialize7();
        initialize8();
    }
    
    private static final void initialize1()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.ForumImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.ForumImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("areas", eu.arcangelovicedomini.javaforum.core.domain.AreaImpl.class)
                }
            )
        );
    }
    
    private static final void initialize2()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.AreaImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.AreaImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("forum", eu.arcangelovicedomini.javaforum.core.domain.ForumImpl.class), 
                    new AssociationType("sections", eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class)
                }
            )
        );
    }
    
    private static final void initialize3()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("area", eu.arcangelovicedomini.javaforum.core.domain.AreaImpl.class), 
                    new AssociationType("threads", eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl.class), 
                    new AssociationType("childSections", eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class), 
                    new AssociationType("fatherSection", eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class)
                }
            )
        );
    }
    
    private static final void initialize4()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("posts", eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class), 
                    new AssociationType("section", eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class)
                }
            )
        );
    }
    
    private static final void initialize5()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("thread", eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl.class), 
                    new AssociationType("author", eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class), 
                    new AssociationType("editor", eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class), 
                    new AssociationType("newVersion", eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class), 
                    new AssociationType("oldVersion", eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class)
                }
            )
        );
    }
    
    private static final void initialize6()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.UserImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.UserImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("profile", eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class), 
                    new AssociationType("configurations", eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl.class)
                }
            )
        );
    }
    
    private static final void initialize7()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("posts", eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class), 
                    new AssociationType("postVersionsCommitted", eu.arcangelovicedomini.javaforum.core.domain.PostImpl.class), 
                    new AssociationType("user", eu.arcangelovicedomini.javaforum.core.domain.UserImpl.class)
                }
            )
        );
    }
    
    private static final void initialize8()
    {
        embeddedValuesByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl.class,
            null);
        navigableAssociationEndsByType.put(
            eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl.class,
            java.util.Arrays.asList(
                new AssociationType[] 
                {
                    new AssociationType("user", eu.arcangelovicedomini.javaforum.core.domain.UserImpl.class)
                }
            )
        );
    }
    
    /**
     * Attempts to get the embedded value list for the given type (or returns null
     * if one doesn't exist).
     * 
     * @param type the type of which to retrieve the value.
     * @return the collection of embedded value names.
     */
    public static java.util.Collection getEmbeddedValues(final Class type)
    {
        return (java.util.Collection)embeddedValuesByType.get(type);
    }
    
    /**
     * Gets the type of the navigable association end given the <code>ownerType</code>
     * and <code>name</code>
     *
     * @param ownerType the owner of the association.
     * @param name the name of the association end to find.
     * @return the type of the association end.
     */
    public static Class getNavigableAssociationEndType(final Class ownerType, final String name)
    {
        final java.util.Collection ends = (java.util.Collection)navigableAssociationEndsByType.get(ownerType);
        final AssociationType type = (AssociationType)org.apache.commons.collections.CollectionUtils.find(
            ends,
            new org.apache.commons.collections.Predicate()
            {
                public boolean evaluate(final Object object)
                {
                    return ((AssociationType)object).name.equals(name);
                }
            });
        return type != null ? type.type : null;
    }

    /**
     * A private class storing the association name and type.
     */    
    protected static final class AssociationType
    {
        protected AssociationType(final String name, final Class type)
        {
            this.name = name;
            this.type = type;
        }
        protected String name;
        protected Class type;
    }
}