// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>eu.arcangelovicedomini.javaforum.core.domain.Forum</code>.
 * </p>
 *
 * @see eu.arcangelovicedomini.javaforum.core.domain.Forum
 */
public abstract class ForumDaoBase
    extends org.springframework.orm.hibernate.support.HibernateDaoSupport
    implements eu.arcangelovicedomini.javaforum.core.domain.ForumDao
{

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#load(int, java.lang.Long)
     */
    public java.lang.Object load(final int transform, final java.lang.Long forumId)
    {
        if (forumId == null)
        {
            throw new IllegalArgumentException(
                "Forum.load - 'forumId' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(eu.arcangelovicedomini.javaforum.core.domain.ForumImpl.class, forumId);
        return transformEntity(transform, (eu.arcangelovicedomini.javaforum.core.domain.Forum)entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#load(java.lang.Long)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Forum load(java.lang.Long forumId)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Forum)this.load(TRANSFORM_NONE, forumId);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum> loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(eu.arcangelovicedomini.javaforum.core.domain.ForumImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#create(eu.arcangelovicedomini.javaforum.core.domain.Forum)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Forum create(eu.arcangelovicedomini.javaforum.core.domain.Forum forum)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Forum)this.create(TRANSFORM_NONE, forum);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#create(int transform, eu.arcangelovicedomini.javaforum.core.domain.Forum)
     */
    public java.lang.Object create(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Forum forum)
    {
        if (forum == null)
        {
            throw new IllegalArgumentException(
                "Forum.create - 'forum' can not be null");
        }
        this.getHibernateTemplate().save(forum);
        return this.transformEntity(transform, forum);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum> create(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum> entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#create(int, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum>)
     */
    public java.util.Collection create(final int transform, final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Forum.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (eu.arcangelovicedomini.javaforum.core.domain.Forum)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#create(java.lang.String, java.lang.String)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Forum create(
        java.lang.String title,
        java.lang.String description)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Forum)this.create(TRANSFORM_NONE, title, description);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#create(int, java.lang.String, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String title,
        java.lang.String description)
    {
        eu.arcangelovicedomini.javaforum.core.domain.Forum entity = new eu.arcangelovicedomini.javaforum.core.domain.ForumImpl();
        entity.setTitle(title);
        entity.setDescription(description);
        return this.create(transform, entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#update(eu.arcangelovicedomini.javaforum.core.domain.Forum)
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.Forum forum)
    {
        if (forum == null)
        {
            throw new IllegalArgumentException(
                "Forum.update - 'forum' can not be null");
        }
        this.getHibernateTemplate().update(forum);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum>)
     */
    public void update(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Forum.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((eu.arcangelovicedomini.javaforum.core.domain.Forum)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#remove(eu.arcangelovicedomini.javaforum.core.domain.Forum)
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.Forum forum)
    {
        if (forum == null)
        {
            throw new IllegalArgumentException(
                "Forum.remove - 'forum' can not be null");
        }
        this.getHibernateTemplate().delete(forum);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long forumId)
    {
        if (forumId == null)
        {
            throw new IllegalArgumentException(
                "Forum.remove - 'forumId' can not be null");
        }
        eu.arcangelovicedomini.javaforum.core.domain.Forum entity = this.load(forumId);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ForumDao#remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum>)
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Forum> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Forum.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>eu.arcangelovicedomini.javaforum.core.domain.ForumDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link eu.arcangelovicedomini.javaforum.core.domain.ForumDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Forum entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Forum)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>eu.arcangelovicedomini.javaforum.core.domain.ForumDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Forum)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}