// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>eu.arcangelovicedomini.javaforum.core.domain.Profile</code>.
 * </p>
 *
 * @see eu.arcangelovicedomini.javaforum.core.domain.Profile
 */
public abstract class ProfileDaoBase
    extends org.springframework.orm.hibernate.support.HibernateDaoSupport
    implements eu.arcangelovicedomini.javaforum.core.domain.ProfileDao
{

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#load(int, java.lang.Long)
     */
    public java.lang.Object load(final int transform, final java.lang.Long profileId)
    {
        if (profileId == null)
        {
            throw new IllegalArgumentException(
                "Profile.load - 'profileId' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class, profileId);
        return transformEntity(transform, (eu.arcangelovicedomini.javaforum.core.domain.Profile)entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#load(java.lang.Long)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Profile load(java.lang.Long profileId)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Profile)this.load(TRANSFORM_NONE, profileId);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile> loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(eu.arcangelovicedomini.javaforum.core.domain.Profile)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Profile create(eu.arcangelovicedomini.javaforum.core.domain.Profile profile)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Profile)this.create(TRANSFORM_NONE, profile);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(int transform, eu.arcangelovicedomini.javaforum.core.domain.Profile)
     */
    public java.lang.Object create(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Profile profile)
    {
        if (profile == null)
        {
            throw new IllegalArgumentException(
                "Profile.create - 'profile' can not be null");
        }
        this.getHibernateTemplate().save(profile);
        return this.transformEntity(transform, profile);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile> create(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile> entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(int, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile>)
     */
    public java.util.Collection create(final int transform, final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Profile.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (eu.arcangelovicedomini.javaforum.core.domain.Profile)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.util.Date)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Profile create(
        java.lang.String name,
        java.lang.String surname,
        java.lang.String prefix,
        java.lang.String suffix,
        java.util.Date birthDate)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Profile)this.create(TRANSFORM_NONE, name, surname, prefix, suffix, birthDate);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.util.Date)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String name,
        java.lang.String surname,
        java.lang.String prefix,
        java.lang.String suffix,
        java.util.Date birthDate)
    {
        eu.arcangelovicedomini.javaforum.core.domain.Profile entity = new eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl();
        entity.setName(name);
        entity.setSurname(surname);
        entity.setPrefix(prefix);
        entity.setSuffix(suffix);
        entity.setBirthDate(birthDate);
        return this.create(transform, entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(java.util.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Profile create(
        java.util.Date birthDate,
        java.lang.String name,
        java.lang.String prefix,
        java.lang.String suffix,
        java.lang.String surname,
        eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Profile)this.create(TRANSFORM_NONE, birthDate, name, prefix, suffix, surname, user);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#create(int, java.util.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    public java.lang.Object create(
        final int transform,
        java.util.Date birthDate,
        java.lang.String name,
        java.lang.String prefix,
        java.lang.String suffix,
        java.lang.String surname,
        eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        eu.arcangelovicedomini.javaforum.core.domain.Profile entity = new eu.arcangelovicedomini.javaforum.core.domain.ProfileImpl();
        entity.setBirthDate(birthDate);
        entity.setName(name);
        entity.setPrefix(prefix);
        entity.setSuffix(suffix);
        entity.setSurname(surname);
        entity.setUser(user);
        return this.create(transform, entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#update(eu.arcangelovicedomini.javaforum.core.domain.Profile)
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.Profile profile)
    {
        if (profile == null)
        {
            throw new IllegalArgumentException(
                "Profile.update - 'profile' can not be null");
        }
        this.getHibernateTemplate().update(profile);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile>)
     */
    public void update(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Profile.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((eu.arcangelovicedomini.javaforum.core.domain.Profile)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#remove(eu.arcangelovicedomini.javaforum.core.domain.Profile)
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.Profile profile)
    {
        if (profile == null)
        {
            throw new IllegalArgumentException(
                "Profile.remove - 'profile' can not be null");
        }
        this.getHibernateTemplate().delete(profile);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long profileId)
    {
        if (profileId == null)
        {
            throw new IllegalArgumentException(
                "Profile.remove - 'profileId' can not be null");
        }
        eu.arcangelovicedomini.javaforum.core.domain.Profile entity = this.load(profileId);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ProfileDao#remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile>)
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Profile> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Profile.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>eu.arcangelovicedomini.javaforum.core.domain.ProfileDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link eu.arcangelovicedomini.javaforum.core.domain.ProfileDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Profile entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Profile)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>eu.arcangelovicedomini.javaforum.core.domain.ProfileDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Profile)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}