// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * @see eu.arcangelovicedomini.javaforum.core.domain.Thread
 */
public class ThreadImpl
    extends eu.arcangelovicedomini.javaforum.core.domain.Thread
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5014929886250293423L;

}