// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * 
 */
public abstract class Thread
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5014929886250293423L;

    private java.lang.Long threadId;

    /**
     * 
     */
    public java.lang.Long getThreadId()
    {
        return this.threadId;
    }

    public void setThreadId(java.lang.Long threadId)
    {
        this.threadId = threadId;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.EnumThreadStatus status;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.EnumThreadStatus getStatus()
    {
        return this.status;
    }

    public void setStatus(eu.arcangelovicedomini.javaforum.core.domain.EnumThreadStatus status)
    {
        this.status = status;
    }

    private java.lang.String title;

    /**
     * 
     */
    public java.lang.String getTitle()
    {
        return this.title;
    }

    public void setTitle(java.lang.String title)
    {
        this.title = title;
    }

    private java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Post> posts = new java.util.HashSet<eu.arcangelovicedomini.javaforum.core.domain.Post>();

    /**
     * 
     */
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Post> getPosts()
    {
        return this.posts;
    }

    public void setPosts(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Post> posts)
    {
        this.posts = posts;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Section section;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Section getSection()
    {
        return this.section;
    }

    public void setSection(eu.arcangelovicedomini.javaforum.core.domain.Section section)
    {
        this.section = section;
    }

    /**
     * Returns <code>true</code> if the argument is an Thread instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Thread))
        {
            return false;
        }
        final Thread that = (Thread)object;
        if (this.threadId == null || that.getThreadId() == null || !this.threadId.equals(that.getThreadId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (threadId == null ? 0 : threadId.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link eu.arcangelovicedomini.javaforum.core.domain.Thread}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Thread}.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Thread newInstance()
        {
            return new eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl();
        }

        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Thread}, taking all required and/or
         * read-only properties as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Thread newInstance(eu.arcangelovicedomini.javaforum.core.domain.EnumThreadStatus status, java.lang.String title, eu.arcangelovicedomini.javaforum.core.domain.Section section)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.Thread entity = new eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl();
            entity.setStatus(status);
            entity.setTitle(title);
            entity.setSection(section);
            return entity;
        }

        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Thread}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Thread newInstance(eu.arcangelovicedomini.javaforum.core.domain.EnumThreadStatus status, java.lang.String title, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Post> posts, eu.arcangelovicedomini.javaforum.core.domain.Section section)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.Thread entity = new eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl();
            entity.setStatus(status);
            entity.setTitle(title);
            entity.setPosts(posts);
            entity.setSection(section);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}