// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>eu.arcangelovicedomini.javaforum.core.domain.User</code>.
 * </p>
 *
 * @see eu.arcangelovicedomini.javaforum.core.domain.User
 */
public abstract class UserDaoBase
    extends org.springframework.orm.hibernate.support.HibernateDaoSupport
    implements eu.arcangelovicedomini.javaforum.core.domain.UserDao
{

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#load(int, java.lang.Long)
     */
    public java.lang.Object load(final int transform, final java.lang.Long userId)
    {
        if (userId == null)
        {
            throw new IllegalArgumentException(
                "User.load - 'userId' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(eu.arcangelovicedomini.javaforum.core.domain.UserImpl.class, userId);
        return transformEntity(transform, (eu.arcangelovicedomini.javaforum.core.domain.User)entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#load(java.lang.Long)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.User load(java.lang.Long userId)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.User)this.load(TRANSFORM_NONE, userId);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User> loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(eu.arcangelovicedomini.javaforum.core.domain.UserImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.User create(eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.User)this.create(TRANSFORM_NONE, user);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(int transform, eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    public java.lang.Object create(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        if (user == null)
        {
            throw new IllegalArgumentException(
                "User.create - 'user' can not be null");
        }
        this.getHibernateTemplate().save(user);
        return this.transformEntity(transform, user);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User> create(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User> entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(int, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User>)
     */
    public java.util.Collection create(final int transform, final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "User.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (eu.arcangelovicedomini.javaforum.core.domain.User)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(java.lang.String, java.lang.String)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.User create(
        java.lang.String userName,
        java.lang.String password)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.User)this.create(TRANSFORM_NONE, userName, password);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(int, java.lang.String, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        java.lang.String userName,
        java.lang.String password)
    {
        eu.arcangelovicedomini.javaforum.core.domain.User entity = new eu.arcangelovicedomini.javaforum.core.domain.UserImpl();
        entity.setUserName(userName);
        entity.setPassword(password);
        return this.create(transform, entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration, java.lang.String, eu.arcangelovicedomini.javaforum.core.domain.Profile, java.lang.String)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.User create(
        java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> configurations,
        java.lang.String password,
        eu.arcangelovicedomini.javaforum.core.domain.Profile profile,
        java.lang.String userName)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.User)this.create(TRANSFORM_NONE, configurations, password, profile, userName);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#create(int, eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration, java.lang.String, eu.arcangelovicedomini.javaforum.core.domain.Profile, java.lang.String)
     */
    public java.lang.Object create(
        final int transform,
        java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> configurations,
        java.lang.String password,
        eu.arcangelovicedomini.javaforum.core.domain.Profile profile,
        java.lang.String userName)
    {
        eu.arcangelovicedomini.javaforum.core.domain.User entity = new eu.arcangelovicedomini.javaforum.core.domain.UserImpl();
        entity.setConfigurations(configurations);
        entity.setPassword(password);
        entity.setProfile(profile);
        entity.setUserName(userName);
        return this.create(transform, entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#update(eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        if (user == null)
        {
            throw new IllegalArgumentException(
                "User.update - 'user' can not be null");
        }
        this.getHibernateTemplate().update(user);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User>)
     */
    public void update(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "User.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((eu.arcangelovicedomini.javaforum.core.domain.User)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#remove(eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        if (user == null)
        {
            throw new IllegalArgumentException(
                "User.remove - 'user' can not be null");
        }
        this.getHibernateTemplate().delete(user);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long userId)
    {
        if (userId == null)
        {
            throw new IllegalArgumentException(
                "User.remove - 'userId' can not be null");
        }
        eu.arcangelovicedomini.javaforum.core.domain.User entity = this.load(userId);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserDao#remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User>)
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.User> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "User.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>eu.arcangelovicedomini.javaforum.core.domain.UserDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link eu.arcangelovicedomini.javaforum.core.domain.UserDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.User entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.User)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>eu.arcangelovicedomini.javaforum.core.domain.UserDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.User)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}