// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoImpl.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;
/**
 * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration
 */
public class UserConfigurationDaoImpl
    extends eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDaoBase
{
}