// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>eu.arcangelovicedomini.javaforum.core.domain.Section</code>.
 * </p>
 *
 * @see eu.arcangelovicedomini.javaforum.core.domain.Section
 */
public abstract class SectionDaoBase
    extends org.springframework.orm.hibernate.support.HibernateDaoSupport
    implements eu.arcangelovicedomini.javaforum.core.domain.SectionDao
{

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#load(int, java.lang.Long)
     */
    public java.lang.Object load(final int transform, final java.lang.Long sectionId)
    {
        if (sectionId == null)
        {
            throw new IllegalArgumentException(
                "Section.load - 'sectionId' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class, sectionId);
        return transformEntity(transform, (eu.arcangelovicedomini.javaforum.core.domain.Section)entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#load(java.lang.Long)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Section load(java.lang.Long sectionId)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Section)this.load(TRANSFORM_NONE, sectionId);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section> loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(eu.arcangelovicedomini.javaforum.core.domain.SectionImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#create(eu.arcangelovicedomini.javaforum.core.domain.Section)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Section create(eu.arcangelovicedomini.javaforum.core.domain.Section section)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Section)this.create(TRANSFORM_NONE, section);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#create(int transform, eu.arcangelovicedomini.javaforum.core.domain.Section)
     */
    public java.lang.Object create(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Section section)
    {
        if (section == null)
        {
            throw new IllegalArgumentException(
                "Section.create - 'section' can not be null");
        }
        this.getHibernateTemplate().save(section);
        return this.transformEntity(transform, section);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section> create(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section> entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#create(int, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section>)
     */
    public java.util.Collection create(final int transform, final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Section.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (eu.arcangelovicedomini.javaforum.core.domain.Section)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#update(eu.arcangelovicedomini.javaforum.core.domain.Section)
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.Section section)
    {
        if (section == null)
        {
            throw new IllegalArgumentException(
                "Section.update - 'section' can not be null");
        }
        this.getHibernateTemplate().update(section);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section>)
     */
    public void update(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Section.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((eu.arcangelovicedomini.javaforum.core.domain.Section)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#remove(eu.arcangelovicedomini.javaforum.core.domain.Section)
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.Section section)
    {
        if (section == null)
        {
            throw new IllegalArgumentException(
                "Section.remove - 'section' can not be null");
        }
        this.getHibernateTemplate().delete(section);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long sectionId)
    {
        if (sectionId == null)
        {
            throw new IllegalArgumentException(
                "Section.remove - 'sectionId' can not be null");
        }
        eu.arcangelovicedomini.javaforum.core.domain.Section entity = this.load(sectionId);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.SectionDao#remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section>)
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Section> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Section.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>eu.arcangelovicedomini.javaforum.core.domain.SectionDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link eu.arcangelovicedomini.javaforum.core.domain.SectionDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Section entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Section)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>eu.arcangelovicedomini.javaforum.core.domain.SectionDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Section)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}