// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>eu.arcangelovicedomini.javaforum.core.domain.Thread</code>.
 * </p>
 *
 * @see eu.arcangelovicedomini.javaforum.core.domain.Thread
 */
public abstract class ThreadDaoBase
    extends org.springframework.orm.hibernate.support.HibernateDaoSupport
    implements eu.arcangelovicedomini.javaforum.core.domain.ThreadDao
{

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#load(int, java.lang.Long)
     */
    public java.lang.Object load(final int transform, final java.lang.Long threadId)
    {
        if (threadId == null)
        {
            throw new IllegalArgumentException(
                "Thread.load - 'threadId' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl.class, threadId);
        return transformEntity(transform, (eu.arcangelovicedomini.javaforum.core.domain.Thread)entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#load(java.lang.Long)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Thread load(java.lang.Long threadId)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Thread)this.load(TRANSFORM_NONE, threadId);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread> loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(eu.arcangelovicedomini.javaforum.core.domain.ThreadImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#create(eu.arcangelovicedomini.javaforum.core.domain.Thread)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Thread create(eu.arcangelovicedomini.javaforum.core.domain.Thread thread)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.Thread)this.create(TRANSFORM_NONE, thread);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#create(int transform, eu.arcangelovicedomini.javaforum.core.domain.Thread)
     */
    public java.lang.Object create(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Thread thread)
    {
        if (thread == null)
        {
            throw new IllegalArgumentException(
                "Thread.create - 'thread' can not be null");
        }
        this.getHibernateTemplate().save(thread);
        return this.transformEntity(transform, thread);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread> create(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread> entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#create(int, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread>)
     */
    public java.util.Collection create(final int transform, final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Thread.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (eu.arcangelovicedomini.javaforum.core.domain.Thread)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#update(eu.arcangelovicedomini.javaforum.core.domain.Thread)
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.Thread thread)
    {
        if (thread == null)
        {
            throw new IllegalArgumentException(
                "Thread.update - 'thread' can not be null");
        }
        this.getHibernateTemplate().update(thread);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread>)
     */
    public void update(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Thread.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((eu.arcangelovicedomini.javaforum.core.domain.Thread)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#remove(eu.arcangelovicedomini.javaforum.core.domain.Thread)
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.Thread thread)
    {
        if (thread == null)
        {
            throw new IllegalArgumentException(
                "Thread.remove - 'thread' can not be null");
        }
        this.getHibernateTemplate().delete(thread);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long threadId)
    {
        if (threadId == null)
        {
            throw new IllegalArgumentException(
                "Thread.remove - 'threadId' can not be null");
        }
        eu.arcangelovicedomini.javaforum.core.domain.Thread entity = this.load(threadId);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.ThreadDao#remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread>)
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Thread> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "Thread.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>eu.arcangelovicedomini.javaforum.core.domain.ThreadDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link eu.arcangelovicedomini.javaforum.core.domain.ThreadDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.Thread entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Thread)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>eu.arcangelovicedomini.javaforum.core.domain.ThreadDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.Thread)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}