// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringDao.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * @see eu.arcangelovicedomini.javaforum.core.domain.Area
 */
public interface AreaDao
{
    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p/>
     * This specific flag denotes no transformation will occur.
     */
    public final static int TRANSFORM_NONE = 0;

    /**
     * Loads an instance of eu.arcangelovicedomini.javaforum.core.domain.Area from the persistent store.
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Area load(java.lang.Long areaId);

    /**
     * <p>
     * Does the same thing as {@link #load(java.lang.Long)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined in this class then the result <strong>WILL BE</strong> passed through an operation which can
     * optionally transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     *
     * @param areaId the identifier of the entity to load.
     * @return either the entity or the object transformed from the entity.
     */
    public Object load(int transform, java.lang.Long areaId);

    /**
     * Loads all entities of type {@link eu.arcangelovicedomini.javaforum.core.domain.Area}.
     *
     * @return the loaded entities.
     */
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Area> loadAll();

    /**
     * <p>
     * Does the same thing as {@link #loadAll()} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     *
     * @param transform the flag indicating what transformation to use.
     * @return the loaded entities.
     */
    public java.util.Collection loadAll(final int transform);

    /**
     * Creates an instance of eu.arcangelovicedomini.javaforum.core.domain.Area and adds it to the persistent store.
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Area create(eu.arcangelovicedomini.javaforum.core.domain.Area area);

    /**
     * <p>
     * Does the same thing as {@link #create(eu.arcangelovicedomini.javaforum.core.domain.Area)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     */
    public Object create(int transform, eu.arcangelovicedomini.javaforum.core.domain.Area area);

    /**
     * Creates a new instance of eu.arcangelovicedomini.javaforum.core.domain.Area and adds
     * from the passed in <code>entities</code> collection
     *
     * @param entities the collection of eu.arcangelovicedomini.javaforum.core.domain.Area
     * instances to create.
     *
     * @return the created instances.
     */
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Area> create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Area> entities);

    /**
     * <p>
     * Does the same thing as {@link #create(eu.arcangelovicedomini.javaforum.core.domain.Area)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entities (into value objects for example). By default, transformation does
     * not occur.
     * </p>
     */
    public java.util.Collection create(int transform, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Area> entities);

    /**
     * Updates the <code>area</code> instance in the persistent store.
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.Area area);

    /**
     * Updates all instances in the <code>entities</code> collection in the persistent store.
     */
    public void update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Area> entities);

    /**
     * Removes the instance of eu.arcangelovicedomini.javaforum.core.domain.Area from the persistent store.
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.Area area);

    /**
     * Removes the instance of eu.arcangelovicedomini.javaforum.core.domain.Area having the given
     * <code>identifier</code> from the persistent store.
     */
    public void remove(java.lang.Long areaId);

    /**
     * Removes all entities in the given <code>entities<code> collection.
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.Area> entities);

}
