// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * 
 */
public abstract class Area
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -8058752111642518049L;

    private java.lang.Long areaId;

    /**
     * 
     */
    public java.lang.Long getAreaId()
    {
        return this.areaId;
    }

    public void setAreaId(java.lang.Long areaId)
    {
        this.areaId = areaId;
    }

    private java.lang.String title;

    /**
     * 
     */
    public java.lang.String getTitle()
    {
        return this.title;
    }

    public void setTitle(java.lang.String title)
    {
        this.title = title;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Forum forum;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Forum getForum()
    {
        return this.forum;
    }

    public void setForum(eu.arcangelovicedomini.javaforum.core.domain.Forum forum)
    {
        this.forum = forum;
    }

    private java.util.Set<eu.arcangelovicedomini.javaforum.core.domain.Section> sections = new java.util.HashSet<eu.arcangelovicedomini.javaforum.core.domain.Section>();

    /**
     * 
     */
    public java.util.Set<eu.arcangelovicedomini.javaforum.core.domain.Section> getSections()
    {
        return this.sections;
    }

    public void setSections(java.util.Set<eu.arcangelovicedomini.javaforum.core.domain.Section> sections)
    {
        this.sections = sections;
    }

    /**
     * Returns <code>true</code> if the argument is an Area instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Area))
        {
            return false;
        }
        final Area that = (Area)object;
        if (this.areaId == null || that.getAreaId() == null || !this.areaId.equals(that.getAreaId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (areaId == null ? 0 : areaId.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link eu.arcangelovicedomini.javaforum.core.domain.Area}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Area}.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Area newInstance()
        {
            return new eu.arcangelovicedomini.javaforum.core.domain.AreaImpl();
        }

        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Area}, taking all required and/or
         * read-only properties as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Area newInstance(java.lang.String title, eu.arcangelovicedomini.javaforum.core.domain.Forum forum)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.Area entity = new eu.arcangelovicedomini.javaforum.core.domain.AreaImpl();
            entity.setTitle(title);
            entity.setForum(forum);
            return entity;
        }

        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Area}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Area newInstance(java.lang.String title, eu.arcangelovicedomini.javaforum.core.domain.Forum forum, java.util.Set<eu.arcangelovicedomini.javaforum.core.domain.Section> sections)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.Area entity = new eu.arcangelovicedomini.javaforum.core.domain.AreaImpl();
            entity.setTitle(title);
            entity.setForum(forum);
            entity.setSections(sections);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}