// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * 
 */
public abstract class Post
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4007626275325189842L;

    private java.lang.Long postId;

    /**
     * 
     */
    public java.lang.Long getPostId()
    {
        return this.postId;
    }

    public void setPostId(java.lang.Long postId)
    {
        this.postId = postId;
    }

    private java.lang.String title;

    /**
     * 
     */
    public java.lang.String getTitle()
    {
        return this.title;
    }

    public void setTitle(java.lang.String title)
    {
        this.title = title;
    }

    private java.lang.String message;

    /**
     * 
     */
    public java.lang.String getMessage()
    {
        return this.message;
    }

    public void setMessage(java.lang.String message)
    {
        this.message = message;
    }

    private java.sql.Timestamp createdOn;

    /**
     * 
     */
    public java.sql.Timestamp getCreatedOn()
    {
        return this.createdOn;
    }

    public void setCreatedOn(java.sql.Timestamp createdOn)
    {
        this.createdOn = createdOn;
    }

    private java.sql.Timestamp editedOn;

    /**
     * 
     */
    public java.sql.Timestamp getEditedOn()
    {
        return this.editedOn;
    }

    public void setEditedOn(java.sql.Timestamp editedOn)
    {
        this.editedOn = editedOn;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Thread thread;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Thread getThread()
    {
        return this.thread;
    }

    public void setThread(eu.arcangelovicedomini.javaforum.core.domain.Thread thread)
    {
        this.thread = thread;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Profile author;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Profile getAuthor()
    {
        return this.author;
    }

    public void setAuthor(eu.arcangelovicedomini.javaforum.core.domain.Profile author)
    {
        this.author = author;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Profile editor;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Profile getEditor()
    {
        return this.editor;
    }

    public void setEditor(eu.arcangelovicedomini.javaforum.core.domain.Profile editor)
    {
        this.editor = editor;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Post newVersion;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Post getNewVersion()
    {
        return this.newVersion;
    }

    public void setNewVersion(eu.arcangelovicedomini.javaforum.core.domain.Post newVersion)
    {
        this.newVersion = newVersion;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.Post oldVersion;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.Post getOldVersion()
    {
        return this.oldVersion;
    }

    public void setOldVersion(eu.arcangelovicedomini.javaforum.core.domain.Post oldVersion)
    {
        this.oldVersion = oldVersion;
    }

    /**
     * Returns <code>true</code> if the argument is an Post instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Post))
        {
            return false;
        }
        final Post that = (Post)object;
        if (this.postId == null || that.getPostId() == null || !this.postId.equals(that.getPostId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (postId == null ? 0 : postId.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link eu.arcangelovicedomini.javaforum.core.domain.Post}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Post}.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Post newInstance()
        {
            return new eu.arcangelovicedomini.javaforum.core.domain.PostImpl();
        }

        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Post}, taking all required and/or
         * read-only properties as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Post newInstance(java.lang.String title, java.lang.String message, java.sql.Timestamp createdOn, eu.arcangelovicedomini.javaforum.core.domain.Thread thread, eu.arcangelovicedomini.javaforum.core.domain.Profile author)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.Post entity = new eu.arcangelovicedomini.javaforum.core.domain.PostImpl();
            entity.setTitle(title);
            entity.setMessage(message);
            entity.setCreatedOn(createdOn);
            entity.setThread(thread);
            entity.setAuthor(author);
            return entity;
        }

        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.Post}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.Post newInstance(java.lang.String title, java.lang.String message, java.sql.Timestamp createdOn, java.sql.Timestamp editedOn, eu.arcangelovicedomini.javaforum.core.domain.Thread thread, eu.arcangelovicedomini.javaforum.core.domain.Profile author, eu.arcangelovicedomini.javaforum.core.domain.Profile editor, eu.arcangelovicedomini.javaforum.core.domain.Post newVersion, eu.arcangelovicedomini.javaforum.core.domain.Post oldVersion)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.Post entity = new eu.arcangelovicedomini.javaforum.core.domain.PostImpl();
            entity.setTitle(title);
            entity.setMessage(message);
            entity.setCreatedOn(createdOn);
            entity.setEditedOn(editedOn);
            entity.setThread(thread);
            entity.setAuthor(author);
            entity.setEditor(editor);
            entity.setNewVersion(newVersion);
            entity.setOldVersion(oldVersion);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}