// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: SpringHibernateDaoBase.vsl in andromda-spring-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration</code>.
 * </p>
 *
 * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration
 */
public abstract class UserConfigurationDaoBase
    extends org.springframework.orm.hibernate.support.HibernateDaoSupport
    implements eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao
{

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#load(int, java.lang.Long)
     */
    public java.lang.Object load(final int transform, final java.lang.Long userConfigurationId)
    {
        if (userConfigurationId == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.load - 'userConfigurationId' can not be null");
        }
        final java.lang.Object entity = this.getHibernateTemplate().get(eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl.class, userConfigurationId);
        return transformEntity(transform, (eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)entity);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#load(java.lang.Long)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration load(java.lang.Long userConfigurationId)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)this.load(TRANSFORM_NONE, userConfigurationId);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#loadAll()
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> loadAll()
    {
        return this.loadAll(TRANSFORM_NONE);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#loadAll(int)
     */
    public java.util.Collection loadAll(final int transform)
    {
        final java.util.Collection results = this.getHibernateTemplate().loadAll(eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl.class);
        this.transformEntities(transform, results);
        return results;
    }


    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#create(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)
     */
    public eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration create(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration userConfiguration)
    {
        return (eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)this.create(TRANSFORM_NONE, userConfiguration);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#create(int transform, eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)
     */
    public java.lang.Object create(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration userConfiguration)
    {
        if (userConfiguration == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.create - 'userConfiguration' can not be null");
        }
        this.getHibernateTemplate().save(userConfiguration);
        return this.transformEntity(transform, userConfiguration);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#create(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration>)
     */
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> create(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> entities)
    {
        return create(TRANSFORM_NONE, entities);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#create(int, java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration>)
     */
    public java.util.Collection create(final int transform, final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.create - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        create(transform, (eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
        return entities;
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#update(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)
     */
    public void update(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration userConfiguration)
    {
        if (userConfiguration == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.update - 'userConfiguration' can not be null");
        }
        this.getHibernateTemplate().update(userConfiguration);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#update(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration>)
     */
    public void update(final java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.update - 'entities' can not be null");
        }
        this.getHibernateTemplate().execute(
            new org.springframework.orm.hibernate.HibernateCallback()
            {
                public java.lang.Object doInHibernate(net.sf.hibernate.Session session)
                    throws net.sf.hibernate.HibernateException
                {
                    for (java.util.Iterator entityIterator = entities.iterator(); entityIterator.hasNext();)
                    {
                        update((eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)entityIterator.next());
                    }
                    return null;
                }
            },
            true);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#remove(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)
     */
    public void remove(eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration userConfiguration)
    {
        if (userConfiguration == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.remove - 'userConfiguration' can not be null");
        }
        this.getHibernateTemplate().delete(userConfiguration);
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#remove(java.lang.Long)
     */
    public void remove(java.lang.Long userConfigurationId)
    {
        if (userConfigurationId == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.remove - 'userConfigurationId' can not be null");
        }
        eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration entity = this.load(userConfigurationId);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * @see eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao#remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration>)
     */
    public void remove(java.util.Collection<eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "UserConfiguration.remove - 'entities' can not be null");
        }
        this.getHibernateTemplate().deleteAll(entities);
    }
    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,java.util.Collection)
     */
    protected java.lang.Object transformEntity(final int transform, final eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration entity)
    {
        java.lang.Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)}
     * method. This method does not instantiate a new collection.
     * <p/>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration)
     */
    protected void transformEntities(final int transform, final java.util.Collection entities)
    {
        switch (transform)
        {
            case TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

}