// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package eu.arcangelovicedomini.javaforum.core.domain;

/**
 * 
 */
public abstract class UserConfiguration
    implements java.io.Serializable
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1786281281815671002L;

    private java.lang.Long userConfigurationId;

    /**
     * 
     */
    public java.lang.Long getUserConfigurationId()
    {
        return this.userConfigurationId;
    }

    public void setUserConfigurationId(java.lang.Long userConfigurationId)
    {
        this.userConfigurationId = userConfigurationId;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.EnumAccessType accessType;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.EnumAccessType getAccessType()
    {
        return this.accessType;
    }

    public void setAccessType(eu.arcangelovicedomini.javaforum.core.domain.EnumAccessType accessType)
    {
        this.accessType = accessType;
    }

    private java.lang.String attribute;

    /**
     * 
     */
    public java.lang.String getAttribute()
    {
        return this.attribute;
    }

    public void setAttribute(java.lang.String attribute)
    {
        this.attribute = attribute;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.EnumVisibilityType visibility;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.EnumVisibilityType getVisibility()
    {
        return this.visibility;
    }

    public void setVisibility(eu.arcangelovicedomini.javaforum.core.domain.EnumVisibilityType visibility)
    {
        this.visibility = visibility;
    }

    private eu.arcangelovicedomini.javaforum.core.domain.User user;

    /**
     * 
     */
    public eu.arcangelovicedomini.javaforum.core.domain.User getUser()
    {
        return this.user;
    }

    public void setUser(eu.arcangelovicedomini.javaforum.core.domain.User user)
    {
        this.user = user;
    }

    /**
     * Returns <code>true</code> if the argument is an UserConfiguration instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof UserConfiguration))
        {
            return false;
        }
        final UserConfiguration that = (UserConfiguration)object;
        if (this.userConfigurationId == null || that.getUserConfigurationId() == null || !this.userConfigurationId.equals(that.getUserConfigurationId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (userConfigurationId == null ? 0 : userConfigurationId.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration}.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration newInstance()
        {
            return new eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl();
        }


        /**
         * Constructs a new instance of {@link eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration}, taking all possible properties
         * (except the identifier(s))as arguments.
         */
        public static eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration newInstance(eu.arcangelovicedomini.javaforum.core.domain.EnumAccessType accessType, java.lang.String attribute, eu.arcangelovicedomini.javaforum.core.domain.EnumVisibilityType visibility, eu.arcangelovicedomini.javaforum.core.domain.User user)
        {
            final eu.arcangelovicedomini.javaforum.core.domain.UserConfiguration entity = new eu.arcangelovicedomini.javaforum.core.domain.UserConfigurationImpl();
            entity.setAccessType(accessType);
            entity.setAttribute(attribute);
            entity.setVisibility(visibility);
            entity.setUser(user);
            return entity;
        }
    }
    
// HibernateEntity.vsl merge-point
}